namespace Serenity_Security.Models.DTOs;

public class AssetCreateUpdateDto
{
    public string SystemName { get; set; }
    public string IpAddress { get; set; }
    public string OsVersion { get; set; }
    public int SystemTypeId { get; set; }
    public bool IsActive { get; set; }
}


// For creation, the id is generated by the database; for updates, it's in the route URL
